# Generated by Django 5.1 on 2024-09-04 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='qty',
        ),
    ]
