# Generated by Django 5.1 on 2024-09-04 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0006_remove_wishlist_qty'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('email_address', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('postal_code', models.BigIntegerField()),
                ('country', models.CharField(max_length=200)),
                ('phone_number', models.BigIntegerField(verbose_name=0)),
                ('is_default', models.BooleanField(default=True, verbose_name='Default')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
