# Generated by Django 5.1 on 2024-09-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0007_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=0, verbose_name='Default'),
        ),
    ]
