# Generated by Django 5.1 on 2024-09-06 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0009_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='aid',
            field=models.ForeignKey(blank=True, db_column='aid', null=True, on_delete=django.db.models.deletion.CASCADE, to='store_app.address'),
        ),
    ]
