# Generated by Django 5.1 on 2024-09-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0012_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
