# Generated by Django 5.1 on 2024-09-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0013_contact_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='mobile',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
